export { default as extend } from './extend';
export { default as PlacementSlot } from '../common/components/PlacementSlot';
export { default as PlacementState } from '../common/states/PlacementState';
export { default as placements, setPlacements } from '../common/placements';
export { registerRenderer, rendererFor } from '../common/renderers';
export { report, flush, device } from '../common/beacon';
export { watchViewability, requiredRatio } from '../common/viewability';
export { withinCap, timesSeen, recordSeen } from '../common/frequency';
export { stickyChoice, remember } from '../common/sticky';
export { setConsent, consentGranted, mayLoadWithConsent, whenConsented } from '../common/consent';
